load('output\setsFile.mat')

run findWindowSize
run windowEdges
run sets_stats.m
run analyze_sets_intersections.m
run analyze_sets.m
run computeFrequency.m

%%

load('output/results')

mb = msgbox({['the max frequency is ' num2str(mxy)]...
    ['the min frequency is ' num2str(mny)]...
    ['the mean frequency is ' num2str(mean_fq)]...
    ['the average joint length is ' num2str(mean_l)]...
    ['there are ' num2str(num_joints) ' joints']...
    ['the total joint length is ' num2str(sum_length)]...
    ['there are ' num2str(totalints) ' intersections']...
    ['the length in x is ' num2str(length_x)]...
    ['the length in y is ' num2str(length_y)]...
    ['the area  ' num2str(area_xy)]})